[workspace]
resolver = "3"
members = [
    "crates/zprove-core",
    "crates/zprove-bench",
    "crates/zprove-revm-tests",
    "crates/p3-uni-stark",
]

[patch.crates-io]
p3-uni-stark = { path = "crates/p3-uni-stark" }
